
#Props from AS 6 total
LungfishCall = "Lungfish Call" 
GloriasTrophy = "Gloria's Trophy" 
StraightJacket = "Straight Jacket" 
LobatoPainting = "Lobato Painting" 
Cake = "Cake" 
LilisBracelet = "Lilis Bracelet"

#Props from MM 6 total
PropSign = "Prop Sign" 
PropFlowers = "Prop Flowers" 
PropPlunger = "Prop Plunger"
PropHedgeTrimmers = "Prop HedgeTrimmers"
PropRollingPin = "Prop Rolling Pin"
PropWaterCan = "Prop Watering Can"

#Current Props from TH 3 total
Candle1 = "Candle1"
Candle2 = "Candle2"
Megaphone = "Megaphone"

#Props from WW 3 total
FredsLetter = "Fred's Letter"
PricelessCoin = "Priceless Coin"
Musket = "Musket"

#19 Psi Powers 
Marksmanship1 = "Marksmanship 1"
Marksmanship2 = "Marksmanship 2"
Marksmanship3 = "Marksmanship 3"
Pyrokinesis1 = "Pyrokinesis 1"
Pyrokinesis2 = "Pyrokinesis 2"
Confusion1 = "Confusion 1"
Confusion2 = "Confusion 2"
Levitation1 = "Levitation 1"
Levitation2 = "Levitation 2"
Levitation3 = "Levitation 3"
Telekinesis1 = "Telekinesis 1"
Telekinesis2 = "Telekinesis 2"
Invisibility1 = "Invisibility 1"
Invisibility2 = "Invisibility 2"
Clairvoyance1 = "Clairvoyance 1"
Clairvoyance2 = "Clairvoyance 2"
Shield1 = "Shield 1"
Shield2 = "Shield 2"
Shield3 = "Shield 3"

#6 Max Ammo Up
AmmoUp1 = "Ammo Up 1"
AmmoUp2 = "Ammo Up 2"
AmmoUp3 = "Ammo Up 3"
AmmoUp4 = "Ammo Up 4"
AmmoUp5 = "Ammo Up 5"
AmmoUp6 = "Ammo Up 6"

#6 Max Lives Up
MaxLivesUp1 = "Max Lives Up 1"
MaxLivesUp2 = "Max Lives Up 2"
MaxLivesUp3 = "Max Lives Up 3"
MaxLivesUp4 = "Max Lives Up 4"
MaxLivesUp5 = "Max Lives Up 5"
MaxLivesUp6 = "Max Lives Up 6"

#4 Confusion Ammo Up
ConfusionUp1 = "Confusion Up 1"
ConfusionUp2 = "Confusion Up 2"
ConfusionUp3 = "Confusion Up 3"
ConfusionUp4 = "Confusion Up 4"

#10 Challenge Challenge Markers
ChallengeMarker1 = "Challenge Marker 1"
ChallengeMarker2 = "Challenge Marker 2"
ChallengeMarker3 = "Challenge Marker 3"
ChallengeMarker4 = "Challenge Marker 4"
ChallengeMarker5 = "Challenge Marker 5"
ChallengeMarker6 = "Challenge Marker 6"
ChallengeMarker7 = "Challenge Marker 7"
ChallengeMarker8 = "Challenge Marker 8"
ChallengeMarker9 = "Challenge Marker 9"
ChallengeMarker10 = "Challenge Marker 10"

#19 Brain Jars, Unique Names
BrainJarElton = "Brain Jar Elton"
BrainJarBobby = "Brain Jar Bobby"
BrainJarDogen = "Brain Jar Dogen"
BrainJarBenny = "Brain Jar Benny"
BrainJarElka = "Brain Jar Elka"
BrainJarKitty = "Brain Jar Kitty"
BrainJarChloe = "Brain Jar Chloe"
BrainJarFranke = "Brain Jar Franke"
BrainJarJT = "Brain Jar JT"
BrainJarQuentin = "Brain Jar Quentin"
BrainJarVernon = "Brain Jar Vernon"
BrainJarMilka = "Brain Jar Milka"
BrainJarCrystal = "Brain Jar Crystal"
BrainJarClem = "Brain Jar Clem"
BrainJarNils = "Brain Jar Nils"
BrainJarMaloof = "Brain Jar Maloof"
BrainJarMikhail = "Brain Jar Mikhail"
BrainJarPhoebe = "Brain Jar Phoebe"
BrainJarChops = "Brain Jar Chops"

#16 Scavenger Hunt Items, Unique Names, in Order
GoldDoubloon = "Gold Doubloon"
EagleClaw = "Eagle Claw"
DiversHelmet = "Divers Helmet"
PsyComic = "Psy Comic"
WoodPipe = "Wood Pipe"
TurkeySandwich = "Turkey Sandwich"
VoodooDoll = "Voodoo Doll"
MinerSkull = "Miner Skull"
PirateScope = "Pirate Scope"
GoldenAcorn = "Golden Acorn"
GlassEye = "Glass Eye"
Egg = "Egg"
FertilityIdol = "Fertility Idol"
DinosaurBone = "Dinosaur Bone"
Fossil = "Fossil"
GoldWatch = "Gold Watch"

#50 Emotional Baggage Tags, 10 of each Type
SuitcaseTag1 = "Suitcase Tag 1"
SuitcaseTag2 = "Suitcase Tag 2"
SuitcaseTag3 = "Suitcase Tag 3"
SuitcaseTag4 = "Suitcase Tag 4"
SuitcaseTag5 = "Suitcase Tag 5"
SuitcaseTag6 = "Suitcase Tag 6"
SuitcaseTag7 = "Suitcase Tag 7"
SuitcaseTag8 = "Suitcase Tag 8"
SuitcaseTag9 = "Suitcase Tag 9"
SuitcaseTag10 = "Suitcase Tag 10"

PurseTag1 = "Purse Tag 1"
PurseTag2 = "Purse Tag 2"
PurseTag3 = "Purse Tag 3"
PurseTag4 = "Purse Tag 4"
PurseTag5 = "Purse Tag 5"
PurseTag6 = "Purse Tag 6"
PurseTag7 = "Purse Tag 7"
PurseTag8 = "Purse Tag 8"
PurseTag9 = "Purse Tag 9"
PurseTag10 = "Purse Tag 10"

HatboxTag1 = "Hatbox Tag 1"
HatboxTag2 = "Hatbox Tag 2"
HatboxTag3 = "Hatbox Tag 3"
HatboxTag4 = "Hatbox Tag 4"
HatboxTag5 = "Hatbox Tag 5"
HatboxTag6 = "Hatbox Tag 6"
HatboxTag7 = "Hatbox Tag 7"
HatboxTag8 = "Hatbox Tag 8"
HatboxTag9 = "Hatbox Tag 9"
HatboxTag10 = "Hatbox Tag 10"

SteamerTag1 = "Steamer Tag 1"
SteamerTag2 = "Steamer Tag 2"
SteamerTag3 = "Steamer Tag 3"
SteamerTag4 = "Steamer Tag 4"
SteamerTag5 = "Steamer Tag 5"
SteamerTag6 = "Steamer Tag 6"
SteamerTag7 = "Steamer Tag 7"
SteamerTag8 = "Steamer Tag 8"
SteamerTag9 = "Steamer Tag 9"
SteamerTag10 = "Steamer Tag 10"

DuffleTag1 = "Duffle Tag 1"
DuffleTag2 = "Duffle Tag 2"
DuffleTag3 = "Duffle Tag 3"
DuffleTag4 = "Duffle Tag 4"
DuffleTag5 = "Duffle Tag 5"
DuffleTag6 = "Duffle Tag 6"
DuffleTag7 = "Duffle Tag 7"
DuffleTag8 = "Duffle Tag 8"
DuffleTag9 = "Duffle Tag 9"
DuffleTag10 = "Duffle Tag 10"

#50 Emotional Baggage, 10 of each Type
Suitcase1 = "Suitcase 1"
Suitcase2 = "Suitcase 2"
Suitcase3 = "Suitcase 3"
Suitcase4 = "Suitcase 4"
Suitcase5 = "Suitcase 5"
Suitcase6 = "Suitcase 6"
Suitcase7 = "Suitcase 7"
Suitcase8 = "Suitcase 8"
Suitcase9 = "Suitcase 9"
Suitcase10 = "Suitcase 10"

Purse1 = "Purse 1"
Purse2 = "Purse 2"
Purse3 = "Purse 3"
Purse4 = "Purse 4"
Purse5 = "Purse 5"
Purse6 = "Purse 6"
Purse7 = "Purse 7"
Purse8 = "Purse 8"
Purse9 = "Purse 9"
Purse10 = "Purse 10"

Hatbox1 = "Hatbox 1"
Hatbox2 = "Hatbox 2"
Hatbox3 = "Hatbox 3"
Hatbox4 = "Hatbox 4"
Hatbox5 = "Hatbox 5"
Hatbox6 = "Hatbox 6"
Hatbox7 = "Hatbox 7"
Hatbox8 = "Hatbox 8"
Hatbox9 = "Hatbox 9"
Hatbox10 = "Hatbox 10"

Steamertrunk1 = "Steamertrunk 1"
Steamertrunk2 = "Steamertrunk 2"
Steamertrunk3 = "Steamertrunk 3"
Steamertrunk4 = "Steamertrunk 4"
Steamertrunk5 = "Steamertrunk 5"
Steamertrunk6 = "Steamertrunk 6"
Steamertrunk7 = "Steamertrunk 7"
Steamertrunk8 = "Steamertrunk 8"
Steamertrunk9 = "Steamertrunk 9"
Steamertrunk10 = "Steamertrunk 10"

Dufflebag1 = "Dufflebag 1"
Dufflebag2 = "Dufflebag 2"
Dufflebag3 = "Dufflebag 3"
Dufflebag4 = "Dufflebag 4"
Dufflebag5 = "Dufflebag 5"
Dufflebag6 = "Dufflebag 6"
Dufflebag7 = "Dufflebag 7"
Dufflebag8 = "Dufflebag 8"
Dufflebag9 = "Dufflebag 9"
Dufflebag10 = "Dufflebag 10"

#19 Vaults
Vault1 = "Vault 1"
Vault2 = "Vault 2"
Vault3 = "Vault 3"
Vault4 = "Vault 4"
Vault5 = "Vault 5"
Vault6 = "Vault 6"
Vault7 = "Vault 7"
Vault8 = "Vault 8"
Vault9 = "Vault 9"
Vault10 = "Vault 10"
Vault11 = "Vault 11"
Vault12 = "Vault 12"
Vault13 = "Vault 13"
Vault14 = "Vault 14"
Vault15 = "Vault 15"
Vault16 = "Vault 16"
Vault17 = "Vault 17"
Vault18 = "Vault 18"
Vault19 = "Vault 19"

#30 Rando Arrowhead Bundles Small
AHSmall1 = "AHSmall 1"
AHSmall2 = "AHSmall 2"
AHSmall3 = "AHSmall 3"
AHSmall4 = "AHSmall 4"
AHSmall5 = "AHSmall 5"
AHSmall6 = "AHSmall 6"
AHSmall7 = "AHSmall 7"
AHSmall8 = "AHSmall 8"
AHSmall9 = "AHSmall 9"
AHSmall10 = "AHSmall 10"
AHSmall11 = "AHSmall 11"
AHSmall12 = "AHSmall 12"
AHSmall13 = "AHSmall 13"
AHSmall14 = "AHSmall 14"
AHSmall15 = "AHSmall 15"
AHSmall16 = "AHSmall 16"
AHSmall17 = "AHSmall 17"
AHSmall18 = "AHSmall 18"
AHSmall19 = "AHSmall 19"
AHSmall20 = "AHSmall 20"
AHSmall21 = "AHSmall 21"
AHSmall22 = "AHSmall 22"
AHSmall23 = "AHSmall 23"
AHSmall24 = "AHSmall 24"
AHSmall25 = "AHSmall 25"
AHSmall26 = "AHSmall 26"
AHSmall27 = "AHSmall 27"
AHSmall28 = "AHSmall 28"
AHSmall29 = "AHSmall 29"
AHSmall30 = "AHSmall 30"

#5 Rando Arrowhead Bundles Large
AHLarge1 = "AHLarge 1"
AHLarge2 = "AHLarge 2"
AHLarge3 = "AHLarge 3"
AHLarge4 = "AHLarge 4"
AHLarge5 = "AHLarge 5"

#111 PsiCards, "Filler" item but rando uses unique names and IDs
PsiCard1 = "PsiCard 1"
PsiCard2 = "PsiCard 2"
PsiCard3 = "PsiCard 3"
PsiCard4 = "PsiCard 4"
PsiCard5 = "PsiCard 5"
PsiCard6 = "PsiCard 6"
PsiCard7 = "PsiCard 7"
PsiCard8 = "PsiCard 8"
PsiCard9 = "PsiCard 9"
PsiCard10 = "PsiCard 10"
PsiCard11 = "PsiCard 11"
PsiCard12 = "PsiCard 12"
PsiCard13 = "PsiCard 13"
PsiCard14 = "PsiCard 14"
PsiCard15 = "PsiCard 15"
PsiCard16 = "PsiCard 16"
PsiCard17 = "PsiCard 17"
PsiCard18 = "PsiCard 18"
PsiCard19 = "PsiCard 19"
PsiCard20 = "PsiCard 20"
PsiCard21 = "PsiCard 21"
PsiCard22 = "PsiCard 22"
PsiCard23 = "PsiCard 23"
PsiCard24 = "PsiCard 24"
PsiCard25 = "PsiCard 25"
PsiCard26 = "PsiCard 26"
PsiCard27 = "PsiCard 27"
PsiCard28 = "PsiCard 28"
PsiCard29 = "PsiCard 29"
PsiCard30 = "PsiCard 30"
PsiCard31 = "PsiCard 31"
PsiCard32 = "PsiCard 32"
PsiCard33 = "PsiCard 33"
PsiCard34 = "PsiCard 34"
PsiCard35 = "PsiCard 35"
PsiCard36 = "PsiCard 36"
PsiCard37 = "PsiCard 37"
PsiCard38 = "PsiCard 38"
PsiCard39 = "PsiCard 39"
PsiCard40 = "PsiCard 40"
PsiCard41 = "PsiCard 41"
PsiCard42 = "PsiCard 42"
PsiCard43 = "PsiCard 43"
PsiCard44 = "PsiCard 44"
PsiCard45 = "PsiCard 45"
PsiCard46 = "PsiCard 46"
PsiCard47 = "PsiCard 47"
PsiCard48 = "PsiCard 48"
PsiCard49 = "PsiCard 49"
PsiCard50 = "PsiCard 50"
PsiCard51 = "PsiCard 51"
PsiCard52 = "PsiCard 52"
PsiCard53 = "PsiCard 53"
PsiCard54 = "PsiCard 54"
PsiCard55 = "PsiCard 55"
PsiCard56 = "PsiCard 56"
PsiCard57 = "PsiCard 57"
PsiCard58 = "PsiCard 58"
PsiCard59 = "PsiCard 59"
PsiCard60 = "PsiCard 60"
PsiCard61 = "PsiCard 61"
PsiCard62 = "PsiCard 62"
PsiCard63 = "PsiCard 63"
PsiCard64 = "PsiCard 64"
PsiCard65 = "PsiCard 65"
PsiCard66 = "PsiCard 66"
PsiCard67 = "PsiCard 67"
PsiCard68 = "PsiCard 68"
PsiCard69 = "PsiCard 69"
PsiCard70 = "PsiCard 70"
PsiCard71 = "PsiCard 71"
PsiCard72 = "PsiCard 72"
PsiCard73 = "PsiCard 73"
PsiCard74 = "PsiCard 74"
PsiCard75 = "PsiCard 75"
PsiCard76 = "PsiCard 76"
PsiCard77 = "PsiCard 77"
PsiCard78 = "PsiCard 78"
PsiCard79 = "PsiCard 79"
PsiCard80 = "PsiCard 80"
PsiCard81 = "PsiCard 81"
PsiCard82 = "PsiCard 82"
PsiCard83 = "PsiCard 83"
PsiCard84 = "PsiCard 84"
PsiCard85 = "PsiCard 85"
PsiCard86 = "PsiCard 86"
PsiCard87 = "PsiCard 87"
PsiCard88 = "PsiCard 88"
PsiCard89 = "PsiCard 89"
PsiCard90 = "PsiCard 90"
PsiCard91 = "PsiCard 91"
PsiCard92 = "PsiCard 92"
PsiCard93 = "PsiCard 93"
PsiCard94 = "PsiCard 94"
PsiCard95 = "PsiCard 95"
PsiCard96 = "PsiCard 96"
PsiCard97 = "PsiCard 97"
PsiCard98 = "PsiCard 98"
PsiCard99 = "PsiCard 99"
PsiCard100 = "PsiCard 100"
PsiCard101 = "PsiCard 101"
PsiCard102 = "PsiCard 102"
PsiCard103 = "PsiCard 103"
PsiCard104 = "PsiCard 104"
PsiCard105 = "PsiCard 105"
PsiCard106 = "PsiCard 106"
PsiCard107 = "PsiCard 107"
PsiCard108 = "PsiCard 108"
PsiCard109 = "PsiCard 109"
PsiCard110 = "PsiCard 110"
PsiCard111 = "PsiCard 111"

#Other Items
OarsmansBadge = "Oarsman's Badge"
Button = "Button"
Feather = "Crow Feather"
CobwebDuster = "Cobweb Duster"

#Needed for Victory!
Victory = "Victory"
