# WHISPERING ROCK SUMMER CAMP
# Sasha's Underground Lab (CASA) 
BehindFurnitureCard = "(CASA) Behind Furniture (Card)"
StaircaseLedgesCard = "(CASA) Staircase Ledges (Card)"
UpperLedgeFossil = "(CASA) Upper Ledge (Fossil)"

# GPC and Wilderness (CAGP) 
TopofGPCCard = "(CAGP) Top of GPC (Card)"
UnderGPCCard = "(CAGP) Under GPC (Card)"
MountainLionLogBridgeCard = "(CAGP) Mountain Lion Log Bridge (Card)"
AboveEntranceLakeCard = "(CAGP) Above Entrance to Lake (Card)"
RockWallBehindTreeCard = "(CAGP) Rock Wall Behind Tree (Card)"
RockWallTopPirateScope = "(CAGP) Rock Wall Top (Pirate Scope)"
TreeNearFenceCard = "(CAGP) Tree Near Fence (Card)"
TreeNearGeyserCard = "(CAGP) Tree Near Geyser (Card)"
FenceBehindGPCCard = "(CAGP) Fence Behind GPC (Card)"
NeartheBearCard = "(CAGP) Near the Bear (Card)"
RockyPlatformsBehindGPCRightCard = "(CAGP) Rocky Platforms Behind GPC Right (Card)"
RockyPlatformsBehindGPCLeftCard = "(CAGP) Rocky Platforms Behind GPC Left (Card)"
TopofLogFlumeCard = "(CAGP) Top of Log Flume (Card)"
RidetheLogFlumeCard = "(CAGP) Ride the Log Flume (Card)"
BottomofLogFlumeCard = "(CAGP) Bottom of Log Flume (Card)"
BigRockNearFordCard = "(CAGP) Big Rock Near Ford (Card)"
RuinedCabinChallengeMarker = "(CAGP) Ruined Cabin (Challenge Marker)"
BranchSwingingCourseStartCard = "(CAGP) Branch Swinging Course Start (Card)"
BranchSwingingCourseMidCard = "(CAGP) Branch Swinging Course Mid (Card)"
BranchSwingingCourseEndChallengeMarker = "(CAGP) Branch Swinging Course End (Challenge Marker)"
BranchAboveSquirrelCard = "(CAGP) Branch Above Squirrel (Card)"
CreekGrateGlassEye = "(CAGP) Creek Grate (Glass Eye)"
SquirrelsAcornGoldenAcorn = "(CAGP) Squirrel's Acorn (Golden Acorn)"
GeyserMinersSkull = "(CAGP) Geyser (Miner's Skull)"

# Main Campgrounds (CAMA) 
FenceNearKidsCabinsCard = "(CAMA) Fence Near Kids' Cabins (Card)"
UnderLodgeFrontStepsCard = "(CAMA) Under Lodge Front Steps (Card)"
BehindTreeNearLodgeCard = "(CAMA) Behind Tree Near Lodge (Card)"
UndertheLodgeGoldDoubloon = "(CAMA) Under the Lodge (Gold Doubloon)"
Loudspeaker1PlatformCard = "(CAMA) Loudspeaker 1 Platform (Card)"
UnderLodgeMetalRoofCard = "(CAMA) Under Lodge Metal Roof (Card)"
LoudspeakerTightropeWalkCard = "(CAMA) Loudspeaker Tightrope Walk (Card)"
Loudspeaker2PlatformCard = "(CAMA) Loudspeaker 2 Platform (Card)"
LodgeRoofChallengeMarker = "(CAMA) Lodge Roof (Challenge Marker)"
MetalRoofOutcroppingCard = "(CAMA) Metal Roof Outcropping (Card)"
LoudspeakerAboveStumpCard = "(CAMA) Loudspeaker Above Stump (Card)"
TreePlatformLeftCard = "(CAMA) Tree Platform Left (Card)"
TreePlatformRightEagleClaw = "(CAMA) Tree Platform Right (Eagle Claw)"
RockWallTopCard = "(CAMA) Rock Wall Top (Card)"
ParkingLotArchCard = "(CAMA) Parking Lot Arch (Card)"
ParkingLotSmallLogCard = "(CAMA) Parking Lot Small Log (Card)"
OleandersCarCard = "(CAMA) Oleander's Car (Card)"
ParkingLotBasketballHoopCard = "(CAMA) Parking Lot Basketball Hoop (Card)"
ParkingLotHistoryBoardCard = "(CAMA) Parking Lot History Board (Card)"
ParkingLotOuthouseCard = "(CAMA) Parking Lot Outhouse (Card)"
RockNearBenchCard = "(CAMA) Rock Near Bench (Card)"

# Kids' Cabins (CAKC) 
GrindingontheRootsCard = "(CAKC) Grinding on the Roots (Card)"
UnderStairsCard = "(CAKC) Under Stairs (Card)"
TopotheLoudspeakerCard = "(CAKC) Top of Loudspeaker (Card)"
CabinRoof1Card = "(CAKC) Cabin Roof 1 (Card)"
TrampolineAboveOuthouseCard = "(CAKC) Trampoline Above Outhouse (Card)"
TrampolinePlatformChallengeMarker = "(CAKC) Trampoline Platform (Challenge Marker)"
CabinsOuthouseCard = "(CAKC) Cabins Outhouse (Card)"
BehindCabinCard = "(CAKC) Behind Cabin (Card)"
RoofofCabin2Card = "(CAKC) Roof of Cabin 2 (Card)"
CaveEntranceCard = "(CAKC) Cave Entrance (Card)"
DeepCavePathCard = "(CAKC) Deep Cave Path (Card)"
DeepCaveLadderCard = "(CAKC) Deep Cave Ladder (Card)"
HighUpTightropeCard = "(CAKC) High-Up Tightrope (Card)"
CaveRefrigeratorTurkeySandwich = "(CAKC) Cave Refrigerator (Turkey Sandwich)"

# Reception Area (CARE) 
GraveyardBearCard = "(CARE) Graveyard Bear (Card)"
NearBeehiveCard = "(CARE) Near Beehive (Card)"
MineshaftTrailerEntranceCard = "(CARE) Mineshaft Trailer Entrance (Card)"
TightropeStartCard = "(CARE) Tightrope Start (Card)"
TightropeEndCard = "(CARE) Tightrope End (Card)"
RocksNearTrailerCard = "(CARE) Rocks Near Trailer (Card)"
FireplaceTreeLowerCard = "(CARE) Fireplace Tree Lower (Card)"
FireplaceTreeRockCard = "(CARE) Fireplace Tree Rock (Card)"
SwampSkinnyPolesCard = "(CARE) Swamp Skinny Poles (Card)"
BigLogPlatformCard = "(CARE) Big Log Platform (Card)"
AboveWaterfallLeftCard = "(CARE) Above Waterfall Left (Card)"
AboveWaterfallRightCard = "(CARE) Above Waterfall Right (Card)"
BehindtheWaterfallCard = "(CARE) Behind the Waterfall (Card)"
WeirdTreeLeftCherryWoodPipe = "(CARE) Weird Tree Left (Cherry Wood Pipe)"
WeirdTreeRightCard = "(CARE) Weird Tree Right (Card)"
LogHillTopCard = "(CARE) Log Hill Top (Card)"
LogHillBehindCard = "(CARE) Log Hill Behind (Card)"
MineshaftGrindRailCard = "(CARE) Mineshaft Grind Rail (Card)"
MineshaftUpperEntranceCard = "(CARE) Mineshaft Upper Entrance (Card)"
MineshaftAboveUpperEntranceCard = "(CARE) Mineshaft Above Upper Entrance (Card)"
InsideMineshaftCard = "(CARE) Inside Mineshaft (Card)"
MineshaftBearCard = "(CARE) Mineshaft Bear (Card)"
SwampBirdsNestCondorEgg = "(CARE) Swamp Bird's Nest (Condor Egg)"
CollapsedCaveChallengeMarker = "(CARE) Collapsed Cave (Challenge Marker)"
FireplaceTreeTopDinosaurBone = "(CARE) Fireplace Tree Top (Dinosaur Bone)"
HornetNestFertilityIdol = "(CARE) Hornet Nest (Fertility Idol)"

# Lake and Boathouse (CABH) 
UndertheFirstBridgeCard = "(CABH) Under the First Bridge (Card)"
BehindStumpCard = "(CABH) Behind Stump (Card)"
LeftofEntranceRockWallCard = "(CABH) Left of Entrance Rock Wall (Card)"
PolesonLakeCard = "(CABH) Poles on Lake (Card)"
BathysphereRoofCard = "(CABH) Bathysphere Roof (Card)"
BathysphereDockCard = "(CABH) Bathysphere Dock (Card)"
MetalRoofAboveFordCard = "(CABH) Metal Roof Above Ford (Card)"
AboveFordRopesCard = "(CABH) Above Ford Ropes (Card)"
AboveFordCabinPlatformCard = "(CABH) Above Ford Cabin Platform (Card)"
OutsideCougarCaveCard = "(CABH) Outside Cougar Cave (Card)"
InsideCougarCaveDiversHelmet = "(CABH) Inside Cougar Cave (Diver's Helmet)"
BulletinBoardBushesCard = "(CABH) Bulletin Board Bushes (Card)"
PinkTreesPlatformLeftCard = "(CABH) Pink Trees Platform Left (Card)"
PinkTreesPlatformRightCard = "(CABH) Pink Trees Platform Right (Card)"
RockWallUpperCard = "(CABH) Rock Wall Upper (Card)"
LakeShoreCard = "(CABH) Lake Shore (Card)"
TinyIslandCard = "(CABH) Tiny Island (Card)"
TopofBigRockChallengeMarker = "(CABH) Top of Big Rock (Challenge Marker)"
RockWallGapPsychonautsComic1 = "(CABH) Rock Wall Gap (Psychonauts Comic # 1)"

# Main Lodge (CALI) 
MainLodgeRaftersVoodooDoll = "(CALI) Main Lodge Rafters (Voodoo Doll)"

# Ford's Sanctuary (CAJA) 
TopofSanctuaryCard = "(CAJA) Top of Sanctuary (Card)"
BottomofSanctuaryCard = "(CAJA) Bottom of Sanctuary (Card)"

# Rando Only Rank Checks (RANK) 
PSIRank05 = "(RANK) PSI Rank 05"
PSIRank10 = "(RANK) PSI Rank 10"
PSIRank15 = "(RANK) PSI Rank 15"
PSIRank20 = "(RANK) PSI Rank 20"
PSIRank25 = "(RANK) PSI Rank 25"
PSIRank30 = "(RANK) PSI Rank 30"
PSIRank35 = "(RANK) PSI Rank 35"
PSIRank40 = "(RANK) PSI Rank 40"
PSIRank45 = "(RANK) PSI Rank 45"
PSIRank50 = "(RANK) PSI Rank 50"
PSIRank55 = "(RANK) PSI Rank 55"
PSIRank60 = "(RANK) PSI Rank 60"
PSIRank65 = "(RANK) PSI Rank 65"
PSIRank70 = "(RANK) PSI Rank 70"
PSIRank75 = "(RANK) PSI Rank 75"
PSIRank80 = "(RANK) PSI Rank 80"
PSIRank85 = "(RANK) PSI Rank 85"
PSIRank90 = "(RANK) PSI Rank 90"
PSIRank95 = "(RANK) PSI Rank 95"
PSIRank101 = "(RANK) PSI Rank 101"

# Asylum Grounds [ASGR] 
RockWallBottom = "(ASGR) Rock Wall Bottom (Lili's Bracelet)"
RockWallLadder = "(ASGR) Rock Wall Ladder (Card)"
OutsideFrontGate = "(ASGR) Outside Front Gate (Challenge Marker)"
PillarAboveGate = "(ASGR) Pillar Above Gate (Card)"
FountainTop = "(ASGR) Fountain Top (Gold Watch)"
HedgeAlcove = "(ASGR) Hedge Alcove (JT's Brain)"
AsylumDoorsRight = "(ASGR) Asylum Doors Right (Franke's Brain)"
AsylumDoorsLeft = "(ASGR) Asylum Doors Left (Card)"
CornerNearFence = "(ASGR) Corner Near Fence (Card)"
LedgeBeforeGloria = "(ASGR) Ledge Before Gloria (Kitty's Brain)"

# Asylum Lower Level [ASCO] 
AboveElevator = "(ASCO) Above Elevator (Card)"
CrowsBasket = "(ASCO) Crow's Basket (Milka's Brain)"
LedgeAboveFredLeft = "(ASCO) Ledge Above Fred Left (Chops' Brain)"
LedgeAboveFredRight = "(ASCO) Ledge Above Fred Right (Card)"
LedgeOppositeElevator = "(ASCO) Ledge Opposite Elevator (Card)"
EdgarsRoom = "(ASCO) Edgar's Room (Card)"
BehindElevator = "(ASCO) Behind Elevator (Maloof's Brain)"
JunkCorner = "(ASCO) Junk Corner (Chloe's Brain)"
AboveEdgar = "(ASCO) Above Edgar (Challenge Marker)"

# Asylum Upper Level [ASUP] 
BehindMattressWall = "(ASUP) Behind Mattress Wall (Card)"
CheckeredBathroom = "(ASUP) Checkered Bathroom (Benny's Brain)"
RoomNearCheckeredBathroom = "(ASUP) Room Near Checkered Bathroom (Card)"
ElevatorShaft = "(ASUP) Elevator Shaft (Card)"
RoomLeftOfPipeSlide = "(ASUP) Room Left of Pipe Slide (Bobby's Brain)"
FloatingInHole = "(ASUP) Floating in Hole (Card)"
NextToHole = "(ASUP) Next to Hole (Card)"
CrumblingOuterWallPlanks = "(ASUP) Crumbling Outer Wall Planks (Elka's Brain)"
CrumblingOuterWallPillar = "(ASUP) Crumbling Outer Wall Pillar (Card)"
CrumblingOuterWallBelowPlatform = "(ASUP) Crumbling Outer Wall Below Platform (Card)"
CrumblingOuterWallPlatform = "(ASUP) Crumbling Outer Wall Platform (Card)"
RoomAboveTiltedStairs = "(ASUP) Room Above Tilted Stairs (Card)"
AcidRoomFloor = "(ASUP) Acid Room Floor (Card)"
AcidRoomTable = "(ASUP) Acid Room Table (Card)"
AcidRoomWindow = "(ASUP) Acid Room Window (Quentin's Brain)"
AcidRoomOverhang = "(ASUP) Acid Room Overhang (Card)"
SmallWindowsLedge = "(ASUP) Small Windows Ledge (Dogen's Brain)"
RoundWoodPlatform = "(ASUP) Round Wood Platform (Card)"
GrateClimbBottom = "(ASUP) Grate Climb Bottom (Phoebe's Brain)"
GrateClimbMid = "(ASUP) Grate Climb Mid (Card)"
SinkPlatformLeft = "(ASUP) Sink Platform Left (Card)"
SinkPlatformRight = "(ASUP) Sink Platform Right (Crystal's Brain)"
PipesBelowChairDoor = "(ASUP) Pipes Below Chair Door (Challenge Marker)"
RoomOppositeChairDoor = "(ASUP) Room Opposite Chair Door (Clem's Brain)"
PipeSlideNearChairDoor = "(ASUP) Pipe Slide Near Chair Door (Card)"
RaftersAboveChairDoor = "(ASUP) Rafters Above Chair Door (Nil's Brain)"

# Dr. Loboto's Laboratory [ASLB] 
LabCagedCrowLeft = "(ASLB) Lab Caged Crow Left (Card)"
LabCagedCrowRight = "(ASLB) Lab Caged Crow Right (Vernon's Brain)"
NextToPokeylope = "(ASLB) Next to Pokeylope (Card)"
LabTopRailingLeft1 = "(ASLB) Lab Top Railing Left 1 (Card)"
LabTopRailingLeft2 = "(ASLB) Lab Top Railing Left 2 (Jarred Brain)"
LabTopElevator = "(ASLB) Lab Top Elevator (Jarred Brain)"
LabTopRailingRight = "(ASLB) Lab Top Railing Right (Card)"
TeaRoom = "(ASLB) Tea Room (Birthday Cake)"

# Obstacle Course 1 [BBA1] 
JumpingTutorial1 = "(BBA1) Jumping Tutorial 1 (Steamer Trunk)"
JumpingTutorial2 = "(BBA1) Jumping Tutorial 2 (Steamer Trunk Tag)"
PoleClimbingTutorialFloor = "(BBA1) Pole-Climbing Tutorial Floor (Suitcase Tag)"
BelowTheTripleTrampolines = "(BBA1) Below the Triple Trampolines (Suitcase)"

# Obstacle Course 2 [BBA2] 
GiantSoldierCutOut = "(BBA2) Giant Soldier Cut-Out (Vault)"
DodgingBullets1 = "(BBA2) Dodging Bullets 1 (Hatbox Tag)"
DodgingBullets2 = "(BBA2) Dodging Bullets 2 (Hatbox)"
MachineGunTurret = "(BBA2) Machine Gun Turret (Dufflebag Tag)"
PoleSwingingTutorial = "(BBA2) Pole-Swinging Tutorial (Dufflebag)"
TrapezeCobweb = "(BBA2) Trapeze Cobweb (Vault)"
TrapezePlatform = "(BBA2) Trapeze Platform (Purse Tag)"
InsidePlaneWreckage = "(BBA2) Inside Plane Wreckage (Purse)"

# Obstacle Course Finale [BBLT] 
EndOfObstacleCourseLeft = "(BBLT) End of Obstacle Course Left"
EndOfObstacleCourseRight = "(BBLT) End of Obstacle Course Right"
BasicBrainingComplete = "(BBLT) Basic Braining Complete"

# Sasha's Shooting Gallery [SACU] 
OnTheBed = "(SACU) On the Bed (Memory Vault)"
OnThePillow = "(SACU) On the Pillow (Dufflebag Tag)"
BuildingBlocksLeft = "(SACU) Building Blocks Left (Hatbox Tag)"
BuildingBlocksBelow = "(SACU) Building Blocks Below (Dufflebag)"
BuildingBlocksRight = "(SACU) Building Blocks Right (One-Up)"
TopOfBedFrame = "(SACU) Top of Bed Frame (Hatbox)"
RoundPlatformsBottom = "(SACU) Round Platforms Bottom (Purse Tag)"
RoundPlatformsNearValve = "(SACU) Round Platforms Near Valve (Purse)"
RoundPlatformsFarFromValve = "(SACU) Round Platforms Far from Valve (One-Up)"
SideOfCubeFace3 = "(SACU) Side of Cube Face 3 (Vault)"
BottomOfShoeboxLadder = "(SACU) Bottom of Shoebox Ladder (Steamer Trunk Tag)"
ShoeboxPedestal = "(SACU) Shoebox Pedestal (Steamer Trunk)"
ShoeboxTowerTop = "(SACU) Shoebox Tower Top (One-Up)"
FlameTowerSteps = "(SACU) Flame Tower Steps (Suitcase Tag)"
FlameTowerTop1 = "(SACU) Flame Tower Top 1 (Suitcase)"
FlameTowerTop2 = "(SACU) Flame Tower Top 2 (One-Up)"
SashasShootingGalleryComplete = "(SACU) Sasha's Shooting Gallery Complete"

# The Lounge [MIFL] 
IntroRingsTutorial = "(MIFL) Intro Rings Tutorial (Dufflebag Tag)"
DancingCamperPlatform1 = "(MIFL) Dancing Camper Platform 1 (Dufflebag)"
DemonRoom = "(MIFL) Demon Room (Memory Vault)"
WindyLadderBottom = "(MIFL) Windy Ladder Bottom (Steamer Trunk Tag)"
PinballPlunger = "(MIFL) Pinball Plunger (Hatbox Tag)"
PlungerPartyLedge = "(MIFL) Plunger Party Ledge (Steamer Trunk)"
GrindrailRings = "(MIFL) Grindrail Rings (Hatbox)"
CensorHallway = "(MIFL) Censor Hallway (Purse Tag)"
PinkBowlBottom = "(MIFL) Pink Bowl Bottom (Vault)"
PinkBowlSmallPlatform = "(MIFL) Pink Bowl Small Platform (Purse)"

# The Party [MILL] 
BubblyFanBottom = "(MILL) Bubbly Fan Bottom (Suitcase Tag)"
BubblyFanPlatform = "(MILL) Bubbly Fan Platform (Ammo Upgrade)"
BubblyFanTop = "(MILL) Bubbly Fan Top (Suitcase)"
MillasPartyRoom = "(MILL) Milla's Party Room"
MillasDancePartyComplete = "(MILL) Milla's Dance Party Complete"

# The Nightmare Woods [NIMP] 
OutsideCaravan = "(NIMP) Outside Caravan (Vault)"
BehindTheEgg = "(NIMP) Behind the Egg (Purse Tag)"
ShadowMonsterPath = "(NIMP) Shadow Monster Path (Steamer Trunk Tag)"
ShadowMonsterBlueMushrooms = "(NIMP) Shadow Monster Blue Mushrooms (Purse)"
LedgeBehindShadowMonster = "(NIMP) Ledge Behind Shadow Monster (Steamer Trunk)"
BelowTheSteepLedge = "(NIMP) Below the Steep Ledge (Dufflebag Tag)"
ForestPathBlueMushrooms = "(NIMP) Forest Path Blue Mushrooms (Suitcase Tag)"
ForestBlueLedge = "(NIMP) Forest Blue Ledge (Suitcase)"
ForestHighPlatform = "(NIMP) Forest High Platform (Dufflebag)"
ForestPathThorns = "(NIMP) Forest Path Thorns (Hatbox Tag)"
BehindThornTowerLeft = "(NIMP) Behind Thorn Tower Left (Hatbox)"
BehindThornTowerMid = "(NIMP) Behind Thorn Tower Mid (Max Lives)"
BehindThornTowerRight = "(NIMP) Behind Thorn Tower Right (Vault)"
BrainTumblerExperimentComplete = "(NIMP) Brain Tumbler Experiment Complete"

# Lungfishopolis City [LOMA] 
SkyscraperStart = "(LOMA) Skyscraper Start (One Up)"
CornerNearJail = "(LOMA) Corner Near Jail (Dufflebag)"
SkyscraperBeforeDam = "(LOMA) Skyscraper before Dam (Purse Tag)"
BehindLasersLeft1 = "(LOMA) Behind Lasers Left 1 (Dufflebag Tag)"
BehindLasersLeft2 = "(LOMA) Behind Lasers Left 2 (Vault)"
BehindLasersRight = "(LOMA) Behind Lasers Right (Purse)"
BlimpHop = "(LOMA) Blimp Hop (Hatbox Tag)"
EndOfDam = "(LOMA) End of Dam (Hatbox)"
EndOfDamPlatform = "(LOMA) End of Dam Platform (One Up)"
SkyscraperAfterDam = "(LOMA) Skyscraper after Dam (Ammo Up)"
NearBattleships = "(LOMA) Near Battleships (Steamertrunk Tag)"
OnTheBridge = "(LOMA) On the Bridge (One Up)"
GroundAfterBridge = "(LOMA) Ground after Bridge (Vault)"
SkyscraperAfterBridge = "(LOMA) Skyscraper after Bridge (Steamertrunk)"
TunnelSuitcaseTag = "(LOMA) Tunnel (Suitcase Tag)"
FinalSkyscrapersLeft = "(LOMA) Final Skyscrapers Left (Max Lives)"
FinalSkyscrapersRight = "(LOMA) Final Skyscrapers Right (Suitcase)"

# Kochamara Arena [LOCB] 
KochamaraIntroLeft = "(LOCB) Kochamara Intro Left"
KochamaraIntroRight = "(LOCB) Kochamara Intro Right"
LungfishopolisComplete = "(LOCB) Lungfishopolis Complete"

# The Neighborhood 1 [MMI1] 
BoydsFridgeClv = "(MMI1) Boyd's Fridge (Clairvoyance)"
FirstHouseDufflebagTag = "(MMI1) First House (Dufflebag Tag)"
SecondHouseRollingPin = "(MMI1) Second House (Rolling Pin)"
CarTrunk1StopSign = "(MMI1) Car Trunk 1 (Stop Sign)"
RoofAfterRoadCrewPurseTag = "(MMI1) Roof after Road Crew (Purse Tag)"
CarTrunk2HedgeTrimmers = "(MMI1) Car Trunk 2 (Hedge Trimmers)"
CarHouseBackyardSteamertrunkTag = "(MMI1) Car House Backyard (Steamertrunk Tag)"
InsideWebbedGarageHatbox = "(MMI1) Inside Webbed Garage (Hatbox)"
GraveyardPatioVault = "(MMI1) Graveyard Patio (Vault)"
GraveyardBehindTreeOneUp = "(MMI1) Graveyard Behind Tree (One Up)"
BehindGraveyardDufflebag = "(MMI1) Behind Graveyard (Dufflebag)"
HedgeMazeFlowers = "(MMI1) Hedge Maze (Flowers)"
CarTrunk3WateringCan = "(MMI1) Car Trunk 3 (Watering Can)"
PostOfficeRoofOneUp = "(MMI1) Post Office Roof (One Up)"
PostOfficeLobbySuitcase = "(MMI1) Post Office Lobby (Suitcase)"
PostOfficeBasementPlunger = "(MMI1) Post Office Basement (Plunger)"
LandscapersHouseBackyardSuitcaseTag = "(MMI1) Landscapers House Backyard (Suitcase Tag)"
LandscapersHouseTablePurse = "(MMI1) Landscapers House Table (Purse)"
LandscapersHouseKitchenAmmoUp = "(MMI1) Landscapers House Kitchen (Ammo Up)"
PowerlineIslandSandboxHatboxTag = "(MMI1) Powerline Island Sandbox (Hatbox Tag)"
PowerlineIslandLeftMemoryVault = "(MMI1) Powerline Island Left (Memory Vault)"
PowerlineIslandRightMaxLives = "(MMI1) Powerline Island Right (Max Lives)"

# The Neighborhood 2 [MMI2] 
BehindBookDepositorySteamerTrunk = "(MMI2) Behind Book Depository (Steamer Trunk)"
MilkmanComplete = "(MMI2) Milkman Complete"

# The Stage [THMS] 
NearTheCriticPurse = "(THMS) Near the Critic (Purse)"
InTheAudienceAmmoUp = "(THMS) In the Audience (Ammo Up)"
BelowTheSpotlightSteamertrunkTag = "(THMS) Below the Spotlight (Steamertrunk Tag)"
BehindStagePurseTag = "(THMS) Behind Stage (Purse Tag)"
BehindStageCobwebSuitcase = "(THMS) Behind Stage Cobweb (Suitcase)"
StorageRoomFloorVault = "(THMS) Storage Room Floor (Vault)"
StorageRoomLeftSteamertrunk = "(THMS) Storage Room Left (Steamertrunk)"
StorageRoomRightLowerSuitcaseTag = "(THMS) Storage Room Right Lower (Suitcase Tag)"
StorageRoomRightUpperCandle1 = "(THMS) Storage Room Right Upper (Candle # 1)"
BonitasRoom = "(THMS) Bonita's Room"

# The Catwalks [THCW] 
DoghouseSlicersDufflebagTag = "(THCW) Doghouse Slicers (Dufflebag Tag)"
BigPlatform1Hatbox = "(THCW) Big Platform 1 (Hatbox)"
BigPlatform2Vault = "(THCW) Big Platform 2 (Vault)"
BigPlatform3OneUp = "(THCW) Big Platform 3 (One Up)"
BigPlatformAboveHatboxTag = "(THCW) Big Platform Above (Hatbox Tag)"
NextToOatmealDufflebag = "(THCW) Next to Oatmeal (Dufflebag)"
CandleBasketCandle2 = "(THCW) Candle Basket (Candle # 2)"
CurtainSlideConfusionAmmoUp = "(THCW) Curtain Slide (Confusion Ammo Up)"
GloriasTheaterComplete = "(THCW) Gloria's Theater Complete"

# WATERLOO WORLD [WWMA] 
FredsRoomHatboxTag = "(WWMA) Fred's Room (Hatbox Tag)"
TheFireplacePricelessCoin = "(WWMA) The Fireplace (Priceless Coin)"
GameBoardSuitcaseTag = "(WWMA) Game Board (Suitcase Tag)"
CarpentersRoofVault = "(WWMA) Carpenter's Roof (Vault)"
TightropeRoomDufflebag = "(WWMA) Tightrope Room (Dufflebag)"
OutsideVillager1HouseOneUp = "(WWMA) Outside Villager 1 House (One Up)"
SmallArchTopMaxLives = "(WWMA) Small Arch Top (Max Lives)"
SmallArchBelowPurseTag = "(WWMA) Small Arch Below (Purse Tag)"
TopOfVillager2sHouseDufflebagTag = "(WWMA) Top of Villager 2's House (Dufflebag Tag)"
TopOfVillager3sHouseAmmoUp = "(WWMA) Top of Villager 3's House (Ammo Up)"
TopOfKnightsHouseConfusionAmmoUp = "(WWMA) Top of Knight's House (Confusion Ammo Up)"
CastleTowerOneUp = "(WWMA) Castle Tower (One Up)"
CastleInsideVault = "(WWMA) Castle Inside (Vault)"
CastleWallSteamertrunk = "(WWMA) Castle Wall (Steamertrunk)"
UnderTheGuillotineSuitcase = "(WWMA) Under the Guillotine (Suitcase)"
FredsHouseBasementHatbox = "(WWMA) Fred's House Basement (Hatbox)"
BlacksmithsLeftBuildingPurse = "(WWMA) Blacksmith's Left Building (Purse)"
BlacksmithsRightBuildingSteamertrunkTag = "(WWMA) Blacksmith's Right Building (Steamertrunk Tag)"
BlacksmithsHaybaleTheMusket = "(WWMA) Blacksmith's Haybale (The Musket)"
HelpTheCarpenter = "(WWMA) Help the Carpenter"
HelpVillager1 = "(WWMA) Help Villager 1"
HelpTheKnight = "(WWMA) Help the Knight"
HelpVillager2 = "(WWMA) Help Villager 2"
HelpVillager3 = "(WWMA) Help Villager 3"
WaterlooWorldComplete = "(WWMA) Waterloo World Complete"

# Running Against the Bull [BVRB] 
ClubStreetLadySteamertrunk = "(BVRB) Club Street Lady (Steamertrunk)"
ClubStreetMetalBalconyDufflebagTag = "(BVRB) Club Street Metal Balcony (Dufflebag Tag)"
HeartStreetHIGHBalconyAmmoUp = "(BVRB) Heart Street HIGH Balcony (Ammo Up)"
AlleywaysLedgeHatboxTag = "(BVRB) Alleyways Ledge (Hatbox Tag)"
SewersMainVault = "(BVRB) Sewers Main (Vault)"
ClubStreetGatedSteamerTrunkTag = "(BVRB) Club Street Gated (Steamer Trunk Tag)"
BurnTheLogsDufflebag = "(BVRB) Burn the Logs (Dufflebag)"
TheGardenVault = "(BVRB) The Garden (Vault)"
NearDiegosHouseMaxLives = "(BVRB) Near Diego's House (Max Lives)"
DiegosBedSuitcaseTag = "(BVRB) Diego's Bed (Suitcase Tag)"
DiegosRoomHatbox = "(BVRB) Diego's Room (Hatbox)"
DiegosHouseGrindrailSuitcase = "(BVRB) Diego's House Grindrail (Suitcase)"
GrindrailBalconyConfusionAmmoUp = "(BVRB) Grindrail Balcony (Confusion Ammo Up)"

# Edgar's Sanctuary [BVES] 
SanctuaryBalconyPurseTag = "(BVES) Sanctuary Balcony (Purse Tag)"
SanctuaryGroundPurse = "(BVES) Sanctuary Ground (Purse)"
TigerWrestler = "(BVES) Tiger Wrestler"
DragonWrestler = "(BVES) Dragon Wrestler"
EagleWrestler = "(BVES) Eagle Wrestler"
CobraWrestler = "(BVES) Cobra Wrestler"
BlackVelvetopiaComplete = "(BVES) Black Velvetopia Complete"

# Meat Circus Main [MCTC] 
EntranceAwningSteamertrunkTag = "(MCTC) Entrance Awning (Steamertrunk Tag)"
CrumblingPathSteamertrunk = "(MCTC) Crumbling Path (Steamertrunk)"
CrumblingPathEndRightHatboxTag = "(MCTC) Crumbling Path End Right (Hatbox Tag)"
CrumblingPathEndLeftConfusionAmmoUp = "(MCTC) Crumbling Path End Left (Confusion Ammo Up)"
OllieEscortFloorSuitcaseTag = "(MCTC) Ollie Escort Floor (Suitcase Tag)"
OllieEscortMiddleHatbox = "(MCTC) Ollie Escort Middle (Hatbox)"
OllieEscortTopLeftVault = "(MCTC) Ollie Escort Top Left (Vault)"
OllieEscortTopRightPurseTag = "(MCTC) Ollie Escort Top Right (Purse Tag)"
TunnelOfLoveStartPurse = "(MCTC) Tunnel of Love Start (Purse)"
TunnelOfLoveCornerSuitcase = "(MCTC) Tunnel of Love Corner (Suitcase)"
TunnelOfLoveRailDufflebagTag = "(MCTC) Tunnel of Love Rail (Dufflebag Tag)"
NextToTheFatLadyDufflebag = "(MCTC) Next to the Fat Lady (Dufflebag)"
FinalBossEvent = "(MCTC) Final Boss Event"

#Ford's Shop
ShopCobwebDuster = "(CALI) Ford's Shop Cobweb Duster"

# DUMMY LOCATIONS
# NOT COLLECTIBLE
DUMMYLOCATION1NOTCOLLECTIBLE = "DUMMY LOCATION 1 (NOT COLLECTIBLE)"
DUMMYLOCATION2NOTCOLLECTIBLE = "DUMMY LOCATION 2 (NOT COLLECTIBLE)"
DUMMYLOCATION3NOTCOLLECTIBLE = "DUMMY LOCATION 3 (NOT COLLECTIBLE)"
