# WHISPERING ROCK SUMMER CAMP
# Sasha's Underground Lab (CASA) 
BehindFurnitureCard = "(CASA) Behind Furniture"
StaircaseLedgesCard = "(CASA) Staircase Ledges"
UpperLedgeFossil = "(CASA) Upper Ledge"

# GPC and Wilderness (CAGP) 
TopofGPCCard = "(CAGP) Top of GPC"
UnderGPCCard = "(CAGP) Under GPC"
MountainLionLogBridgeCard = "(CAGP) Mountain Lion Log Bridge"
AboveEntranceLakeCard = "(CAGP) Above Entrance to Lake"
RockWallBehindTreeCard = "(CAGP) Rock Wall Behind Tree"
RockWallTopPirateScope = "(CAGP) Rock Wall Top"
TreeNearFenceCard = "(CAGP) Tree Near Fence"
TreeNearGeyserCard = "(CAGP) Tree Near Geyser"
FenceBehindGPCCard = "(CAGP) Fence Behind GPC"
NeartheBearCard = "(CAGP) Near the Bear"
RockyPlatformsBehindGPCRightCard = "(CAGP) Rocky Platforms Behind GPC Right"
RockyPlatformsBehindGPCLeftCard = "(CAGP) Rocky Platforms Behind GPC Left"
TopofLogFlumeCard = "(CAGP) Top of Log Flume"
RidetheLogFlumeCard = "(CAGP) Ride the Log Flume"
BottomofLogFlumeCard = "(CAGP) Bottom of Log Flume"
BigRockNearFordCard = "(CAGP) Big Rock Near Ford"
RuinedCabinChallengeMarker = "(CAGP) Inside the Ruined Cabin"
BranchSwingingCourseStartCard = "(CAGP) Branch Swinging Course Start"
BranchSwingingCourseMidCard = "(CAGP) Branch Swinging Course Mid"
BranchSwingingCourseEndChallengeMarker = "(CAGP) Branch Swinging Course End"
BranchAboveSquirrelCard = "(CAGP) Branch Above Squirrel"
CreekGrateGlassEye = "(CAGP) Creek Grate"
SquirrelsAcornGoldenAcorn = "(CAGP) Squirrel's Acorn"
GeyserMinersSkull = "(CAGP) Wedged in the Geyser"

# Main Campgrounds (CAMA) 
FenceNearKidsCabinsCard = "(CAMA) Fence Near Kids' Cabins"
UnderLodgeFrontStepsCard = "(CAMA) Under Lodge Front Steps"
BehindTreeNearLodgeCard = "(CAMA) Behind Tree Near Lodge"
UndertheLodgeGoldDoubloon = "(CAMA) Under the Lodge"
Loudspeaker1PlatformCard = "(CAMA) Loudspeaker 1 Platform"
UnderLodgeMetalRoofCard = "(CAMA) Under Lodge Metal Roof"
LoudspeakerTightropeWalkCard = "(CAMA) Loudspeaker Tightrope Walk"
Loudspeaker2PlatformCard = "(CAMA) Loudspeaker 2 Platform"
LodgeRoofChallengeMarker = "(CAMA) Lodge Roof"
MetalRoofOutcroppingCard = "(CAMA) Metal Roof Outcropping"
LoudspeakerAboveStumpCard = "(CAMA) Loudspeaker Above Stump"
TreePlatformLeftCard = "(CAMA) Tree Platform Left"
TreePlatformRightEagleClaw = "(CAMA) Tree Platform Right"
RockWallTopCard = "(CAMA) Rock Wall Top"
ParkingLotArchCard = "(CAMA) Parking Lot Arch"
ParkingLotSmallLogCard = "(CAMA) Parking Lot Small Log"
OleandersCarCard = "(CAMA) Oleander's Car"
ParkingLotBasketballHoopCard = "(CAMA) Parking Lot Basketball Hoop"
ParkingLotHistoryBoardCard = "(CAMA) Parking Lot History Board"
ParkingLotOuthouseCard = "(CAMA) Parking Lot Outhouse"
RockNearBenchCard = "(CAMA) Rock Near Bench"

# Kids' Cabins (CAKC) 
GrindingontheRootsCard = "(CAKC) Grinding on the Roots"
UnderStairsCard = "(CAKC) Under Stairs"
TopotheLoudspeakerCard = "(CAKC) Top of Loudspeaker"
CabinRoof1Card = "(CAKC) Cabin Roof 1"
TrampolineAboveOuthouseCard = "(CAKC) Trampoline Above Outhouse"
TrampolinePlatformChallengeMarker = "(CAKC) Trampoline Platform"
CabinsOuthouseCard = "(CAKC) Cabins Outhouse"
BehindCabinCard = "(CAKC) Behind Cabin"
RoofofCabin2Card = "(CAKC) Roof of Cabin 2"
CaveEntranceCard = "(CAKC) Cave Entrance"
DeepCavePathCard = "(CAKC) Deep Cave Path"
DeepCaveLadderCard = "(CAKC) Deep Cave Ladder"
HighUpTightropeCard = "(CAKC) High-Up Tightrope"
CaveRefrigeratorTurkeySandwich = "(CAKC) Cave Refrigerator"

# Reception Area (CARE) 
GraveyardBearCard = "(CARE) Graveyard Bear"
NearBeehiveCard = "(CARE) Near Beehive"
MineshaftTrailerEntranceCard = "(CARE) Mineshaft Trailer Entrance"
TightropeStartCard = "(CARE) Tightrope Start"
TightropeEndCard = "(CARE) Tightrope End"
RocksNearTrailerCard = "(CARE) Rocks Near Trailer"
FireplaceTreeLowerCard = "(CARE) Fireplace Tree Lower"
FireplaceTreeRockCard = "(CARE) Fireplace Tree Rock"
SwampSkinnyPolesCard = "(CARE) Swamp Skinny Poles"
BigLogPlatformCard = "(CARE) Big Log Platform"
AboveWaterfallLeftCard = "(CARE) Above Waterfall Left"
AboveWaterfallRightCard = "(CARE) Above Waterfall Right"
BehindtheWaterfallCard = "(CARE) Behind the Waterfall"
WeirdTreeLeftCherryWoodPipe = "(CARE) Weird Tree Left"
WeirdTreeRightCard = "(CARE) Weird Tree Right"
LogHillTopCard = "(CARE) Log Hill Top"
LogHillBehindCard = "(CARE) Log Hill Behind"
MineshaftGrindRailCard = "(CARE) Mineshaft Grind Rail"
MineshaftUpperEntranceCard = "(CARE) Mineshaft Upper Entrance"
MineshaftAboveUpperEntranceCard = "(CARE) Mineshaft Above Upper Entrance"
InsideMineshaftCard = "(CARE) Inside Mineshaft"
MineshaftBearCard = "(CARE) Mineshaft Bear"
SwampBirdsNestCondorEgg = "(CARE) Swamp Bird's Nest"
CollapsedCaveChallengeMarker = "(CARE) Collapsed Cave"
FireplaceTreeTopDinosaurBone = "(CARE) Fireplace Tree Top"
HornetNestFertilityIdol = "(CARE) Hornet Nest"

# Lake and Boathouse (CABH) 
UndertheFirstBridgeCard = "(CABH) Under the First Bridge"
BehindStumpCard = "(CABH) Behind Stump"
LeftofEntranceRockWallCard = "(CABH) Left of Entrance Rock Wall"
PolesonLakeCard = "(CABH) Poles on Lake"
BathysphereRoofCard = "(CABH) Bathysphere Roof"
BathysphereDockCard = "(CABH) Bathysphere Dock"
MetalRoofAboveFordCard = "(CABH) Metal Roof Above Docks"
AboveFordRopesCard = "(CABH) Above Ford Ropes"
AboveFordCabinPlatformCard = "(CABH) Above Ford Cabin Platform"
OutsideCougarCaveCard = "(CABH) Outside Cougar Cave"
InsideCougarCaveDiversHelmet = "(CABH) Inside Cougar Cave"
BulletinBoardBushesCard = "(CABH) Bulletin Board Bushes"
PinkTreesPlatformLeftCard = "(CABH) Pink Trees Platform Left"
PinkTreesPlatformRightCard = "(CABH) Pink Trees Platform Right"
RockWallUpperCard = "(CABH) Rock Wall Upper"
LakeShoreCard = "(CABH) Lake Shore"
TinyIslandCard = "(CABH) Tiny Island"
TopofBigRockChallengeMarker = "(CABH) Top of Big Rock"
RockWallGapPsychonautsComic1 = "(CABH) Rock Wall Gap"

# Main Lodge (CALI) 
MainLodgeRaftersVoodooDoll = "(CALI) Main Lodge Rafters"

# Ford's Sanctuary (CAJA) 
TopofSanctuaryCard = "(CAJA) Top of Sanctuary"
BottomofSanctuaryCard = "(CAJA) Bottom of Sanctuary"
# for redeemeing the required brain jars
RedeemedBrainsEvent = "(CAJA) Redeemed Required Brains"

# Rando Only Rank Checks (RANK) 
PSIRank05 = "(RANK) PSI Rank 05"
PSIRank10 = "(RANK) PSI Rank 10"
PSIRank15 = "(RANK) PSI Rank 15"
PSIRank20 = "(RANK) PSI Rank 20"
PSIRank25 = "(RANK) PSI Rank 25"
PSIRank30 = "(RANK) PSI Rank 30"
PSIRank35 = "(RANK) PSI Rank 35"
PSIRank40 = "(RANK) PSI Rank 40"
PSIRank45 = "(RANK) PSI Rank 45"
PSIRank50 = "(RANK) PSI Rank 50"
PSIRank55 = "(RANK) PSI Rank 55"
PSIRank60 = "(RANK) PSI Rank 60"
PSIRank65 = "(RANK) PSI Rank 65"
PSIRank70 = "(RANK) PSI Rank 70"
PSIRank75 = "(RANK) PSI Rank 75"
PSIRank80 = "(RANK) PSI Rank 80"
PSIRank85 = "(RANK) PSI Rank 85"
PSIRank90 = "(RANK) PSI Rank 90"
PSIRank95 = "(RANK) PSI Rank 95"
PSIRank101 = "(RANK) PSI Rank 101"

# Asylum Grounds [ASGR] 
RockWallBottom = "(ASGR) Rock Wall Bottom"
RockWallLadder = "(ASGR) Rock Wall Ladder"
OutsideFrontGate = "(ASGR) Outside Front Gate"
PillarAboveGate = "(ASGR) Pillar Above Gate"
FountainTop = "(ASGR) Fountain Top"
HedgeAlcove = "(ASGR) Hedge Alcove"
AsylumDoorsRight = "(ASGR) Asylum Doors Right"
AsylumDoorsLeft = "(ASGR) Asylum Doors Left"
CornerNearFence = "(ASGR) Corner Near Fence"
LedgeBeforeGloria = "(ASGR) Ledge Before Gloria"

# Asylum Lower Level [ASCO] 
AboveElevator = "(ASCO) Above Elevator"
CrowsBasket = "(ASCO) Crow's Basket"
LedgeAboveFredLeft = "(ASCO) Ledge Above Fred Left"
LedgeAboveFredRight = "(ASCO) Ledge Above Fred Right"
LedgeOppositeElevator = "(ASCO) Ledge Opposite Elevator"
EdgarsRoom = "(ASCO) Edgar's Room"
BehindElevator = "(ASCO) Behind Elevator"
JunkCorner = "(ASCO) Junk Corner"
AboveEdgar = "(ASCO) Above Edgar"

# Asylum Upper Level [ASUP] 
BehindMattressWall = "(ASUP) Behind Mattress Wall"
CheckeredBathroom = "(ASUP) Checkered Bathroom"
RoomNearCheckeredBathroom = "(ASUP) Room Near Checkered Bathroom"
ElevatorShaft = "(ASUP) Elevator Shaft"
RoomLeftOfPipeSlide = "(ASUP) Room Left of Pipe Slide"
FloatingInHole = "(ASUP) Floating in Hole"
NextToHole = "(ASUP) Next to Hole"
CrumblingOuterWallPlanks = "(ASUP) Crumbling Outer Wall Planks"
CrumblingOuterWallPillar = "(ASUP) Crumbling Outer Wall Pillar"
CrumblingOuterWallBelowPlatform = "(ASUP) Crumbling Outer Wall Below Platform"
CrumblingOuterWallPlatform = "(ASUP) Crumbling Outer Wall Platform"
RoomAboveTiltedStairs = "(ASUP) Room Above Tilted Stairs"
AcidRoomFloor = "(ASUP) Acid Room Floor"
AcidRoomTable = "(ASUP) Acid Room Table"
AcidRoomWindow = "(ASUP) Acid Room Window"
AcidRoomOverhang = "(ASUP) Acid Room Overhang"
SmallWindowsLedge = "(ASUP) Small Windows Ledge"
RoundWoodPlatform = "(ASUP) Round Wood Platform"
GrateClimbBottom = "(ASUP) Grate Climb Bottom"
GrateClimbMid = "(ASUP) Grate Climb Mid"
SinkPlatformLeft = "(ASUP) Sink Platform Left"
SinkPlatformRight = "(ASUP) Sink Platform Right"
PipesBelowChairDoor = "(ASUP) Pipes Below Chair Door"
RoomOppositeChairDoor = "(ASUP) Room Opposite Chair Door"
PipeSlideNearChairDoor = "(ASUP) Pipe Slide Near Chair Door"
RaftersAboveChairDoor = "(ASUP) Rafters Above Chair Door"

# Dr. Loboto's Laboratory [ASLB] 
LabCagedCrowLeft = "(ASLB) Lab Caged Crow Left"
LabCagedCrowRight = "(ASLB) Lab Caged Crow Right"
NextToPokeylope = "(ASLB) Next to Pokeylope"
LabTopRailingLeft1 = "(ASLB) Lab Top Railing Left 1"
LabTopRailingLeft2 = "(ASLB) Lab Top Railing Left 2"
LabTopElevator = "(ASLB) Lab Top Elevator"
LabTopRailingRight = "(ASLB) Lab Top Railing Right"
TeaRoom = "(ASLB) Tea Room"
OleanderBossEvent = "(ASLB) Oleander Boss Defeated"

# Obstacle Course 1 [BBA1] 
JumpingTutorial1 = "(BBA1) Jumping Tutorial 1"
JumpingTutorial2 = "(BBA1) Jumping Tutorial 2"
PoleClimbingTutorialFloor = "(BBA1) Pole-Climbing Tutorial Floor"
BelowTheTripleTrampolines = "(BBA1) Below the Triple Trampolines"

# Obstacle Course 2 [BBA2] 
GiantSoldierCutOut = "(BBA2) Giant Soldier Cut-Out"
DodgingBullets1 = "(BBA2) Dodging Bullets 1"
DodgingBullets2 = "(BBA2) Dodging Bullets 2"
MachineGunTurret = "(BBA2) Machine Gun Turret"
PoleSwingingTutorial = "(BBA2) Pole-Swinging Tutorial"
TrapezeCobweb = "(BBA2) Trapeze Cobweb"
TrapezePlatform = "(BBA2) Trapeze Platform"
InsidePlaneWreckage = "(BBA2) Inside Plane Wreckage"

# Obstacle Course Finale [BBLT] 
EndOfObstacleCourseLeft = "(BBLT) End of Obstacle Course Left"
EndOfObstacleCourseRight = "(BBLT) End of Obstacle Course Right"
BasicBrainingComplete = "(BBLT) Basic Braining Complete"

# Sasha's Shooting Gallery [SACU] 
OnTheBed = "(SACU) On the Bed"
OnThePillow = "(SACU) On the Pillow"
BuildingBlocksLeft = "(SACU) Building Blocks Left"
BuildingBlocksBelow = "(SACU) Building Blocks Below"
BuildingBlocksRight = "(SACU) Building Blocks Right"
TopOfBedFrame = "(SACU) Top of Bed Frame"
RoundPlatformsBottom = "(SACU) Round Platforms Bottom"
RoundPlatformsNearValve = "(SACU) Round Platforms Near Valve"
RoundPlatformsFarFromValve = "(SACU) Round Platforms Far from Valve"
SideOfCubeFace3 = "(SACU) Side of Cube Face 3"
BottomOfShoeboxLadder = "(SACU) Bottom of Shoebox Ladder"
ShoeboxPedestal = "(SACU) Shoebox Pedestal"
ShoeboxTowerTop = "(SACU) Shoebox Tower Top"
FlameTowerSteps = "(SACU) Flame Tower Steps"
FlameTowerTop1 = "(SACU) Flame Tower Top 1"
FlameTowerTop2 = "(SACU) Flame Tower Top 2"
SashasShootingGalleryComplete = "(SACU) Sasha's Shooting Gallery Complete"

# The Lounge [MIFL] 
IntroRingsTutorial = "(MIFL) Intro Rings Tutorial"
DancingCamperPlatform1 = "(MIFL) Dancing Camper Platform 1"
DemonRoom = "(MIFL) Demon Room"
WindyLadderBottom = "(MIFL) Windy Ladder Bottom"
PinballPlunger = "(MIFL) Pinball Plunger"
PlungerPartyLedge = "(MIFL) Plunger Party Ledge"
GrindrailRings = "(MIFL) Grindrail Rings"
CensorHallway = "(MIFL) Censor Hallway"
PinkBowlBottom = "(MIFL) Pink Bowl Bottom"
PinkBowlSmallPlatform = "(MIFL) Pink Bowl Small Platform"

# The Party [MILL] 
BubblyFanBottom = "(MILL) Bubbly Fan Bottom"
BubblyFanPlatform = "(MILL) Bubbly Fan Platform"
BubblyFanTop = "(MILL) Bubbly Fan Top"
MillasPartyRoom = "(MILL) Milla's Party Room"
MillasDancePartyComplete = "(MILL) Milla's Dance Party Complete"

# The Nightmare Woods [NIMP] 
OutsideCaravan = "(NIMP) Outside Caravan"
BehindTheEgg = "(NIMP) Behind the Egg"
ShadowMonsterPath = "(NIMP) Shadow Monster Path"
ShadowMonsterBlueMushrooms = "(NIMP) Shadow Monster Blue Mushrooms"
LedgeBehindShadowMonster = "(NIMP) Ledge Behind Shadow Monster"
BelowTheSteepLedge = "(NIMP) Below the Steep Ledge"
ForestPathBlueMushrooms = "(NIMP) Forest Path Blue Mushrooms"
ForestBlueLedge = "(NIMP) Forest Blue Ledge"
ForestHighPlatform = "(NIMP) Forest High Platform"
ForestPathThorns = "(NIMP) Forest Path Thorns"
BehindThornTowerLeft = "(NIMP) Behind Thorn Tower Left"
BehindThornTowerMid = "(NIMP) Behind Thorn Tower Mid"
BehindThornTowerRight = "(NIMP) Behind Thorn Tower Right"
BrainTumblerExperimentComplete = "(NIMP) Brain Tumbler Experiment Complete"

# Lungfishopolis City [LOMA] 
SkyscraperStart = "(LOMA) Skyscraper Start"
CornerNearJail = "(LOMA) Corner Near Jail"
SkyscraperBeforeDam = "(LOMA) Skyscraper before Dam"
BehindLasersLeft1 = "(LOMA) Behind Lasers Left 1"
BehindLasersLeft2 = "(LOMA) Behind Lasers Left 2"
BehindLasersRight = "(LOMA) Behind Lasers Right"
BlimpHop = "(LOMA) Blimp Hop"
EndOfDam = "(LOMA) End of Dam"
EndOfDamPlatform = "(LOMA) End of Dam Platform"
SkyscraperAfterDam = "(LOMA) Skyscraper after Dam"
NearBattleships = "(LOMA) Near Battleships"
OnTheBridge = "(LOMA) On the Bridge"
GroundAfterBridge = "(LOMA) Ground after Bridge"
SkyscraperAfterBridge = "(LOMA) Skyscraper after Bridge"
TunnelSuitcaseTag = "(LOMA) Train Tunnel"
FinalSkyscrapersLeft = "(LOMA) Final Skyscrapers Left"
FinalSkyscrapersRight = "(LOMA) Final Skyscrapers Right"

# Kochamara Arena [LOCB] 
KochamaraIntroLeft = "(LOCB) Kochamara Intro Left"
KochamaraIntroRight = "(LOCB) Kochamara Intro Right"
LungfishopolisComplete = "(LOCB) Lungfishopolis Complete"

# The Neighborhood 1 [MMI1] 
BoydsFridgeClv = "(MMI1) Boyd's Fridge"
FirstHouseDufflebagTag = "(MMI1) Inside First House"
SecondHouseRollingPin = "(MMI1) Inside Second House"
CarTrunk1StopSign = "(MMI1) Car Trunk 1 (Stop Sign)"
RoofAfterRoadCrewPurseTag = "(MMI1) Roof after Road Crew"
CarTrunk2HedgeTrimmers = "(MMI1) Car Trunk 2"
CarHouseBackyardSteamertrunkTag = "(MMI1) Car House Backyard"
InsideWebbedGarageHatbox = "(MMI1) Inside Webbed Garage"
GraveyardPatioVault = "(MMI1) Graveyard Patio"
GraveyardBehindTreeOneUp = "(MMI1) Graveyard Behind Tree"
BehindGraveyardDufflebag = "(MMI1) Behind Graveyard"
HedgeMazeFlowers = "(MMI1) Hedge Maze"
CarTrunk3WateringCan = "(MMI1) Car Trunk 3"
PostOfficeRoofOneUp = "(MMI1) Post Office Roof"
PostOfficeLobbySuitcase = "(MMI1) Post Office Lobby"
PostOfficeBasementPlunger = "(MMI1) Post Office Basement"
LandscapersHouseBackyardSuitcaseTag = "(MMI1) Landscapers House Backyard"
LandscapersHouseTablePurse = "(MMI1) Landscapers House Table"
LandscapersHouseKitchenAmmoUp = "(MMI1) Landscapers House Kitchen"
PowerlineIslandSandboxHatboxTag = "(MMI1) Powerline Island Sandbox"
PowerlineIslandLeftMemoryVault = "(MMI1) Powerline Island Left"
PowerlineIslandRightMaxLives = "(MMI1) Powerline Island Right"

# The Neighborhood 2 [MMI2] 
BehindBookDepositorySteamerTrunk = "(MMI2) Behind Book Depository"
MilkmanComplete = "(MMI2) Milkman Complete"

# The Stage [THMS] 
NearTheCriticPurse = "(THMS) Near the Critic"
InTheAudienceAmmoUp = "(THMS) In the Audience"
BelowTheSpotlightSteamertrunkTag = "(THMS) Below the Spotlight"
BehindStagePurseTag = "(THMS) Behind Stage"
BehindStageCobwebSuitcase = "(THMS) Behind Stage Cobweb"
StorageRoomFloorVault = "(THMS) Storage Room Floor"
StorageRoomLeftSteamertrunk = "(THMS) Storage Room Left"
StorageRoomRightLowerSuitcaseTag = "(THMS) Storage Room Right Lower"
StorageRoomRightUpperCandle1 = "(THMS) Storage Room Right Upper"
BonitasRoom = "(THMS) Bonita's Room"

# The Catwalks [THCW] 
DoghouseSlicersDufflebagTag = "(THCW) Doghouse Slicers"
BigPlatform1Hatbox = "(THCW) Big Platform 1"
BigPlatform2Vault = "(THCW) Big Platform 2"
BigPlatform3OneUp = "(THCW) Big Platform 3"
BigPlatformAboveHatboxTag = "(THCW) Big Platform Above"
NextToOatmealDufflebag = "(THCW) Next to Oatmeal"
CandleBasketCandle2 = "(THCW) Candle Basket"
CurtainSlideConfusionAmmoUp = "(THCW) Curtain Slide"
GloriasTheaterComplete = "(THCW) Gloria's Theater Complete"

# WATERLOO WORLD [WWMA] 
FredsRoomHatboxTag = "(WWMA) Fred's Room"
TheFireplacePricelessCoin = "(WWMA) The Fireplace"
GameBoardSuitcaseTag = "(WWMA) Game Board"
CarpentersRoofVault = "(WWMA) Carpenter's Roof"
TightropeRoomDufflebag = "(WWMA) Tightrope Room"
OutsideVillager1HouseOneUp = "(WWMA) Outside Villager 1 House"
SmallArchTopMaxLives = "(WWMA) Small Arch Top"
SmallArchBelowPurseTag = "(WWMA) Small Arch Below"
TopOfVillager2sHouseDufflebagTag = "(WWMA) Top of Villager 2's House"
TopOfVillager3sHouseAmmoUp = "(WWMA) Top of Villager 3's House"
TopOfKnightsHouseConfusionAmmoUp = "(WWMA) Top of Knight's House"
CastleTowerOneUp = "(WWMA) Castle Tower"
CastleInsideVault = "(WWMA) Castle Inside"
CastleWallSteamertrunk = "(WWMA) Castle Wall"
UnderTheGuillotineSuitcase = "(WWMA) Under the Guillotine"
FredsHouseBasementHatbox = "(WWMA) Fred's House Basement"
BlacksmithsLeftBuildingPurse = "(WWMA) Blacksmith's Left Building"
BlacksmithsRightBuildingSteamertrunkTag = "(WWMA) Blacksmith's Right Building"
BlacksmithsHaybaleTheMusket = "(WWMA) Blacksmith's Haybale"
HelpTheCarpenter = "(WWMA) Help the Carpenter"
HelpVillager1 = "(WWMA) Help Villager 1"
HelpTheKnight = "(WWMA) Help the Knight"
HelpVillager2 = "(WWMA) Help Villager 2"
HelpVillager3 = "(WWMA) Help Villager 3"
WaterlooWorldComplete = "(WWMA) Waterloo World Complete"

# Running Against the Bull [BVRB] 
ClubStreetLadySteamertrunk = "(BVRB) Club Street Lady"
ClubStreetMetalBalconyDufflebagTag = "(BVRB) Club Street Metal Balcony"
HeartStreetHIGHBalconyAmmoUp = "(BVRB) Heart Street HIGH Balcony"
AlleywaysLedgeHatboxTag = "(BVRB) Alleyways Ledge"
SewersMainVault = "(BVRB) Sewers Main"
ClubStreetGatedSteamerTrunkTag = "(BVRB) Club Street Gated"
BurnTheLogsDufflebag = "(BVRB) Burn the Logs"
TheGardenVault = "(BVRB) The Garden"
NearDiegosHouseMaxLives = "(BVRB) Near Diego's House"
DiegosBedSuitcaseTag = "(BVRB) Diego's Bed"
DiegosRoomHatbox = "(BVRB) Diego's Room"
DiegosHouseGrindrailSuitcase = "(BVRB) Diego's House Grindrail"
GrindrailBalconyConfusionAmmoUp = "(BVRB) Grindrail Balcony"

# Edgar's Sanctuary [BVES] 
SanctuaryBalconyPurseTag = "(BVES) Sanctuary Balcony"
SanctuaryGroundPurse = "(BVES) Sanctuary Ground"
TigerWrestler = "(BVES) Tiger Wrestler"
DragonWrestler = "(BVES) Dragon Wrestler"
EagleWrestler = "(BVES) Eagle Wrestler"
CobraWrestler = "(BVES) Cobra Wrestler"
BlackVelvetopiaComplete = "(BVES) Black Velvetopia Complete"

# Meat Circus Main [MCTC] 
EntranceAwningSteamertrunkTag = "(MCTC) Entrance Awning"
CrumblingPathSteamertrunk = "(MCTC) Crumbling Path"
CrumblingPathEndRightHatboxTag = "(MCTC) Crumbling Path End Right"
CrumblingPathEndLeftConfusionAmmoUp = "(MCTC) Crumbling Path End Left"
OllieEscortFloorSuitcaseTag = "(MCTC) Ollie Escort Floor"
OllieEscortMiddleHatbox = "(MCTC) Ollie Escort Middle"
OllieEscortTopLeftVault = "(MCTC) Ollie Escort Top Left"
OllieEscortTopRightPurseTag = "(MCTC) Ollie Escort Top Right"
TunnelOfLoveStartPurse = "(MCTC) Tunnel of Love Start"
TunnelOfLoveCornerSuitcase = "(MCTC) Tunnel of Love Corner"
TunnelOfLoveRailDufflebagTag = "(MCTC) Tunnel of Love Rail"
NextToTheFatLadyDufflebag = "(MCTC) Next to the Fat Lady"
FinalBossEvent = "(MCTC) Final Boss Defeated"

#Ford's Shop, only a location if Cobweb Duster vanilla
ShopCobwebDuster = "(CALI) Ford's Shop Cobweb Duster"

